version: '3'
services:
  mongo:
    image: mongo:3.4
    volumes:
      - db-mongo-data-local:/data/db
      - db-mongo-conf-local:/data/configdb
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - ikiinet-local                  
##---- INFRASTRUCTURE MICROSERVICES---- ##
  ikii-back-config:
    container_name: ikii-back-config
    image : ikii/config:2.0.0
    restart: always
    ports:
        - "${SERVER_CONFIG_PORT}:8888"  
    networks:
        - ikiinet-local
    logging:
      options:
        max-size: "10m"
        max-file: "10"                     
      
  ikii-back-registry:
    container_name: ikii-back-registry
    image : ikii/registry:2.0.0
    restart: always
    ports:
        - "${SERVER_REGISTRY_PORT}:8761" 
    networks:
        - ikiinet-local
    links:
        - ikii-back-config:ikii-back-config     
    depends_on:
      - ikii-back-config                                   
    logging:
      options:
        max-size: "10m"
        max-file: "10"    
        
  ikii-back-gateway:
    container_name: ikii-back-gateway
    image : ikii/gateway:2.0.0
    ports:
      - "${GATEWAY_PORT}:4000"
    networks:
      - ikiinet-local  
    links:
      - ikii-back-config:ikii-back-config
    depends_on:
      - ikii-back-config
      - ikii-back-registry            

##----FUNCTIONAL MICROSERVICES----##
  ikii-back-customers:
    container_name: ikii-back-customers
    image: ikii/customers:2.0.0
    ports:
      - "${USERS_PORT}:8002"   
      - "9004:8000"
    networks:
      - ikiinet-local 
    links:
      - ikii-back-config:ikii-back-config
    depends_on:
      - ikii-back-config
      - ikii-back-registry
      - mongo 

  ikii-back-security:
    container_name: ikii-back-security
    image : ikii/security:2.0.0
    ports:
      - "${SECURITY_PORT}:8003"  
      - "9005:8000"  
    networks:
      - ikiinet-local 
    links:
      - ikii-back-config:ikii-back-config
    depends_on:
      - ikii-back-config
      - ikii-back-registry
      - mongo                   
                 
networks:
  ikiinet-local:
    driver: bridge
    ipam:
      driver: default

volumes:
  db-mongo-data-local:
  db-mongo-conf-local:
