version: '3'
services:
  mongo:
    image: mongo:3.4
    volumes:
      - db-mongo-data-local:/data/db
      - db-mongo-conf-local:/data/configdb
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - ikiinet-local             
                 
networks:
  ikiinet-local:
    driver: bridge
    ipam:
      driver: default

volumes:
  db-mongo-data-local:
  db-mongo-conf-local:
