package mx.ikii.commons.utils.constants;

public enum EnumCity {

	AGUASCALIENTES,BAJA_CALIFORNIA,BAJA_CALIFORNIA_SUR,CAMPECHE,CDMX,CHIAPAS,CHIHUAHUA,COAHUILA,COLIMA,DURANGO,ESTADO_DE_MEX,
	GUANAJUATO,GUERRERO,HIDALGO,JALISCO,MICHOACAN,MORELOS,NAYARIT,NUEVO_LEON,OAXACA,PUEBLA,QUERETARO,QUINTANA_ROO,
	SAN_LUIS_POTOSI,SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS;
}
